---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: grimoire
spec:
  serviceName: mariadb
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: mariadb:10.0
          name: mariadb
          resources:
            requests:
              cpu: 500m
              memory: 768Mi
            limits:
              cpu: 1000m
              memory: 1.5Gi
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_ALLOW_EMPTY_PASSWORD
          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
