# Site settings
title: GrimoireLab - Software Development and Community Analytics platform
email: info@bitergia.com
description: "GrimoireLab is a 100% free, open source software platform for software development and community analytics. The project is part of the CHAOSS Software community"
baseurl: "/grimoirelab"
url: "http://chaoss.github.io"
twitter_username:
github_username:  GrimoireLab

# Build settings
markdown: kramdown
permalink: pretty
